<?php 
	$this->load->view('layout/head');
	$this->load->view('layout/body');
	$this->load->view('layout/header');
	$this->load->view('layout/content-wrapper');
	$this->load->view('layout/aside');
	$this->load->view('layout/control-sidebar');
	$this->load->view('layout/main-footer');
	$this->load->view('layout/footer');
 ?>